name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Synopsys Detect
      uses: blackducksoftware/github-action@2.0.1
      with:
    # Synopsys Detect arguments
        args: --blackduck.url="${{ secrets.BLACKDUCK_URL}}" --blackduck.api.token="${{ secrets.BLACKDUCK_API_TOKEN}}"
#    - name: Upload to CoPilot
#      if: github.event_name == 'push' || github.event_name == 'pull_request'
#      run: bash <(curl -s https://copilot.blackducksoftware.com/ci/githubactions/scripts/upload)
